[package]
name = "eww-data-requester"
version = "0.1.0"
edition = "2024"

[dependencies]
enums = { path = "../enums" }
postcard = { version = "1.0.8", features = ["alloc"] }
serde = { version = "1.0.203", features = ["derive"] }
