[package]
name = "eww-data-provider"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
inotify = { version = "0.11.0", features = ["tokio"] }
log = "0.4"
env_logger = "0.11"
futures-util = "0.3"
